import { Component } from '@angular/core';

@Component({
  selector: 'app-clients',
  templateUrl: './clients.component.html',
  styleUrls: ['./clients.component.css']
})
export class ClientsComponent {
clientLogos: string[] = [
    "https://websitemetadata.blob.core.windows.net/website/5.%20Client%20Logo/08aed8a9cbb0668ad6d6cb4516410d69.png",
    "https://websitemetadata.blob.core.windows.net/website/5.%20Client%20Logo/1.png",
    "https://websitemetadata.blob.core.windows.net/website/5.%20Client%20Logo/10.png",
    "https://websitemetadata.blob.core.windows.net/website/5.%20Client%20Logo/11.png",
    "https://websitemetadata.blob.core.windows.net/website/5.%20Client%20Logo/12.jpg",
    "https://websitemetadata.blob.core.windows.net/website/5.%20Client%20Logo/12.png",
    "https://websitemetadata.blob.core.windows.net/website/5.%20Client%20Logo/13.png",
    "https://websitemetadata.blob.core.windows.net/website/5.%20Client%20Logo/14.png",
    "https://websitemetadata.blob.core.windows.net/website/5.%20Client%20Logo/15.jpg",
    "https://websitemetadata.blob.core.windows.net/website/5.%20Client%20Logo/16.webp",
    "https://websitemetadata.blob.core.windows.net/website/5.%20Client%20Logo/17.png",
    "https://websitemetadata.blob.core.windows.net/website/5.%20Client%20Logo/18.png",
    "https://websitemetadata.blob.core.windows.net/website/5.%20Client%20Logo/19.png",
    "https://websitemetadata.blob.core.windows.net/website/5.%20Client%20Logo/2.png",
    "https://websitemetadata.blob.core.windows.net/website/5.%20Client%20Logo/20.png",
    "https://websitemetadata.blob.core.windows.net/website/5.%20Client%20Logo/21.jpeg",
    "https://websitemetadata.blob.core.windows.net/website/5.%20Client%20Logo/22.png",
    "https://websitemetadata.blob.core.windows.net/website/5.%20Client%20Logo/23.jpeg",
    "https://websitemetadata.blob.core.windows.net/website/5.%20Client%20Logo/24.webp",
    "https://websitemetadata.blob.core.windows.net/website/5.%20Client%20Logo/25.jpg",
    "https://websitemetadata.blob.core.windows.net/website/5.%20Client%20Logo/26.png",
    "https://websitemetadata.blob.core.windows.net/website/5.%20Client%20Logo/27.webp",
    "https://websitemetadata.blob.core.windows.net/website/5.%20Client%20Logo/28.png",
    "https://websitemetadata.blob.core.windows.net/website/5.%20Client%20Logo/29.png",
    "https://websitemetadata.blob.core.windows.net/website/5.%20Client%20Logo/3.png",
    "https://websitemetadata.blob.core.windows.net/website/5.%20Client%20Logo/30.jpeg",
    "https://websitemetadata.blob.core.windows.net/website/5.%20Client%20Logo/31.png",
    "https://websitemetadata.blob.core.windows.net/website/5.%20Client%20Logo/34894_decathlonlogo_90890.png",
    "https://websitemetadata.blob.core.windows.net/website/5.%20Client%20Logo/4.png",
    // "https://websitemetadata.blob.core.windows.net/website/5.%20Client%20Logo/5.png",
    "https://websitemetadata.blob.core.windows.net/website/5.%20Client%20Logo/59291.jpeg",
    "https://websitemetadata.blob.core.windows.net/website/5.%20Client%20Logo/6.png",
    "https://websitemetadata.blob.core.windows.net/website/5.%20Client%20Logo/7.png",
    "https://websitemetadata.blob.core.windows.net/website/5.%20Client%20Logo/8.png",
    "https://websitemetadata.blob.core.windows.net/website/5.%20Client%20Logo/9.png",
    "https://websitemetadata.blob.core.windows.net/website/5.%20Client%20Logo/BMC_MUMBAI_LOGO.png",
    "https://websitemetadata.blob.core.windows.net/website/5.%20Client%20Logo/Fitizen-Sports-Event-Logo-Final_White-Background-2-scaled.webp",
    "https://websitemetadata.blob.core.windows.net/website/5.%20Client%20Logo/Hyperice-Logo.png",
    //"https://websitemetadata.blob.core.windows.net/website/5.%20Client%20Logo/craycol_wordmark_white_only_logo_698b164b-309d-4b1e-a081-fbe44d0a3c98.png",
    "https://websitemetadata.blob.core.windows.net/website/5.%20Client%20Logo/e693927f0626a7823e87edc86e785d16.png",
    "https://websitemetadata.blob.core.windows.net/website/5.%20Client%20Logo/ezgif.com-gif-maker_316c42d2-0897-40bc-81d1-5119f87bfef7.webp",
    "https://websitemetadata.blob.core.windows.net/website/5.%20Client%20Logo/imgonline-com-ua-resize-jK5SMzfGHeA.jpg",
    "https://websitemetadata.blob.core.windows.net/website/5.%20Client%20Logo/logo.png",
    "https://websitemetadata.blob.core.windows.net/website/5.%20Client%20Logo/tata-ev-logo-70x40-black.webp",
    "https://websitemetadata.blob.core.windows.net/website/5.%20Client%20Logo/ytcrlogo1.png",
    "https://websitemetadata.blob.core.windows.net/website/5.%20Client%20Logo/zixa-stronggel-logo.png"
  ];
}
